name: Daily Discord Item Fetch

on:
  schedule:
    - cron: '30 0 * * *'  # Runs daily at 3:00 AM UTC
  workflow_dispatch:      # Also lets you run manually

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        working-directory: server
        run: npm install

      - name: Run fetch script
        working-directory: server
        env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
          MONGO_URI: ${{ secrets.MONGO_URI }}
        run: node updateMongo.js